[app]
	version = "v 0.1.0"
	title = "MapCloud Tiler"
[output]
	#can be mbtiles/file
	format ="mbtiles"
	#the output dir
	directory ="output"
[task]
	#number of fetchers
	workers = 2
	#number of savers
	savepipe = 1
	#min request interval, a speed limit, unit millisecond
	timedelay = 100

[tm]
	#name for mbtiles
	name = "高德卫星图"
	#max and min level for mbtiles
	min = 0
	max = 15
	#can be pbf/png/jpg
	format = "jpg"
	#can be xyz/tm
	schema = "xyz"
	#the vector tiles metadata tilejson
	# json = ""
	#url is the schema url of tiles

    url = "http://webst01.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}"
#lrs can set diff boundaries for diff levels
  [[lrs]]
  	min = 0
  	max = 15
  	geojson = "./geojson/china.geojson"